In [1]:
import pandas as pd
import numpy as np

In [21]:
fe = pd.read_csv('fullevents.csv')
pe = pd.read_csv('passingevents.csv')
m = pd.read_csv('matches.csv')

In [22]:
#将坐标统一！
def convert_coor(row):
    if row[1].startswith('Opponent'):
        for i in range(1,5):
            row[-i] = 100-row[-i]
    return row
fe = fe.apply(func=convert_coor,axis=1)
pe = pe.apply(func=convert_coor,axis=1)

In [23]:
fe[fe.EventSubType == 'Goal kick'].head(20)

MatchID     TeamID OriginPlayerID DestinationPlayerID MatchPeriod  \
0           1    Huskies     Huskies_G1                 NaN          1H   
98          1  Opponent1   Opponent1_G1                 NaN          1H   
205         1  Opponent1   Opponent1_G1                 NaN          1H   
303         1    Huskies     Huskies_G1                 NaN          1H   
403         1  Opponent1   Opponent1_G1                 NaN          1H   
490         1  Opponent1   Opponent1_G1                 NaN          1H   
532         1  Opponent1   Opponent1_G1                 NaN          1H   
549         1    Huskies     Huskies_G1                 NaN          1H   
563         1    Huskies     Huskies_G1                 NaN          1H   
747         1    Huskies     Huskies_G1                 NaN          2H   
776         1    Huskies     Huskies_G1                 NaN          2H   
797         1    Huskies     Huskies_G1                 NaN          2H   
930         1    Huskies     Huskies_G1                 NaN          2H   
959         1    Huskies     Huskies_D1                 NaN          2H   
1022        1  Opponent1   Opponent1_G1                 NaN          2H   
1245        1  Opponent1   Opponent1_G1                 NaN          2H   
1337        1    Huskies     Huskies_G1                 NaN          2H   
1410        1  Opponent1   Opponent1_G1                 NaN          2H   
1525        2    Huskies     Huskies_G1                 NaN          1H   
1576        2  Opponent2   Opponent2_G1                 NaN          1H   

        EventTime  EventType EventSubType  EventOrigin_x  EventOrigin_y  \
0       31.174681  Free Kick    Goal kick            0.0            0.0   
98     376.493622  Free Kick    Goal kick            0.0            0.0   
205    755.184368  Free Kick    Goal kick            0.0            0.0   
303   1077.943180  Free Kick    Goal kick            0.0            0.0   
403   1467.212071  Free Kick    Goal kick            0.0            0.0   
490   1781.344236  Free Kick    Goal kick            0.0            0.0   
532   1985.539709  Free Kick    Goal kick            0.0            0.0   
549   2072.200206  Free Kick    Goal kick            0.0            0.0   
563   2114.866437  Free Kick    Goal kick            0.0            0.0   
747     49.242968  Free Kick    Goal kick            0.0            0.0   
776    152.632124  Free Kick    Goal kick            0.0            0.0   
797    267.015263  Free Kick    Goal kick            0.0            0.0   
930    697.022220  Free Kick    Goal kick            0.0            0.0   
959    782.730790  Free Kick    Goal kick            0.0            0.0   
1022  1003.281570  Free Kick    Goal kick            0.0            0.0   
1245  1901.437630  Free Kick    Goal kick            0.0            0.0   
1337  2224.882186  Free Kick    Goal kick            0.0            0.0   
1410  2511.531717  Free Kick    Goal kick            0.0            0.0   
1525    34.287353  Free Kick    Goal kick          100.0          100.0   
1576   204.308681  Free Kick    Goal kick          100.0          100.0   

      EventDestination_x  EventDestination_y  
0                   66.0                89.0  
98                  81.0                32.0  
205                 26.0                 5.0  
303                 15.0                18.0  
403                 47.0                 4.0  
490                 21.0                86.0  
532                 36.0                24.0  
549                 69.0                90.0  
563                 39.0                96.0  
747                 18.0                74.0  
776                 54.0                33.0  
797                 81.0                91.0  
930                 94.0                44.0  
959                 46.0                49.0  
1022                37.0                27.0  
1245                43.0                34.0  
1337                74.0                14.0  
1410    

In [10]:
fe.loc[fe.MatchID==1,['OriginPlayerID','DestinationPlayerID',
                      'EventSubType','EventOrigin_x','EventOrigin_y',
                      'EventDestination_x','EventDestination_y']].head(20)

OriginPlayerID DestinationPlayerID            EventSubType  EventOrigin_x  \
0      Huskies_G1                 NaN               Goal kick            0.0   
1    Opponent1_D1                 NaN                Air duel           66.0   
2      Huskies_F1                 NaN                Air duel           66.0   
3    Opponent1_D2                 NaN                Throw in           78.0   
4      Huskies_D1          Huskies_F1               Head pass           34.0   
5      Huskies_F1                 NaN  Ground loose ball duel           59.0   
6    Opponent1_D1                 NaN  Ground loose ball duel           59.0   
7    Opponent1_M1                 NaN             Simple pass           64.0   
8      Huskies_F1                 NaN               Head pass           55.0   
9    Opponent1_D1                 NaN  Ground loose ball duel           57.0   
10     Huskies_M1          Huskies_F2             Simple pass           53.0   
11     Huskies_F2                 NaN             Simple pass           69.0   
12   Opponent1_D2                 NaN                Throw in           70.0   
13     Huskies_F1                 NaN                Throw in           65.0   
14   Opponent1_D2        Opponent1_G1             Simple pass           81.0   
15   Opponent1_G1        Opponent1_F1                  Launch           95.0   
16   Opponent1_F1                 NaN                Air duel           33.0   
17     Huskies_D2                 NaN                Air duel           33.0   
18     Huskies_M2          Huskies_M3             Simple pass           42.0   
19     Huskies_M3                 NaN             Simple pass           36.0   

    EventOrigin_y  EventDestination_x  EventDestination_y  
0            50.0                66.0                89.0  
1            89.0                78.0               100.0  
2            89.0                78.0               100.0  
3           100.0                34.0                97.0  
4            97.0                59.0                95.0  
5            95.0                64.0                94.0  
6            95.0                64.0                94.0  
7            94.0                55.0                95.0  
8            95.0                57.0                93.0  
9            93.0                53.0                89.0  
10           89.0                69.0                91.0  
11           91.0                75.0               100.0  
12          100.0                60.0               100.0  
13          100.0                81.0                84.0  
14           84.0                95.0                50.0  
15           50.0                33.0                56.0  
16           56.0                42.0                55.0  
17           56.0                42.0                55.0  
18           55.0                36.0                54.0  
19           54.0                36.0                63.0

In [24]:
def ball_control_rate(match_id):
    a = pe[pe.MatchID == match_id].TeamID.value_counts()
    h,o = a.iloc[0],a.iloc[1]
    t=h+o
    return h/t, o/t

In [25]:
for i in range(1,38):
    print(ball_control_rate(i), m['Outcome'][i-1])

(0.6519434628975265, 0.3480565371024735) win
(0.697986577181208, 0.30201342281879195) tie
(0.5924528301886792, 0.4075471698113208) loss
(0.5064377682403434, 0.49356223175965663) loss
(0.5059602649006623, 0.49403973509933774) loss
(0.5196078431372549, 0.4803921568627451) win
(0.6820603907637656, 0.31793960923623443) loss
(0.5157342657342657, 0.48426573426573427) tie
(0.7488789237668162, 0.25112107623318386) loss
(0.6265270506108203, 0.37347294938917974) loss
(0.634, 0.366) win
(0.7634408602150538, 0.23655913978494625) tie
(0.6711051930758988, 0.3288948069241012) loss
(0.5, 0.5) win
(0.5474747474747474, 0.45252525252525255) win
(0.8832116788321168, 0.11678832116788321) tie
(0.5435435435435435, 0.45645645645645644) win
(0.50814332247557, 0.49185667752442996) win
(0.6675603217158177, 0.3324396782841823) tie
(0.5, 0.5) tie
(0.6421052631578947, 0.35789473684210527) loss
(0.6657342657342658, 0.33426573426573425) loss
(0.6671368124118476, 0.3328631875881523) loss
(0.6324110671936759, 0.3675889

In [26]:
types = fe['EventSubType'].unique()

In [29]:
p1 = dict(sorted([(x, 0) for x in 
                  pe[(pe.MatchID == 1)]['OriginPlayerID'].unique()]))
p2 = dict(sorted([(x, 0) for x in 
                  pe[(pe.MatchID == 1)]['DestinationPlayerID'].unique()]))

In [30]:
for i in range(len(pe[(pe.MatchID == 1)])):
    p1[pe['OriginPlayerID'][i]] += 1
    p2[pe['DestinationPlayerID'][i]] += 1

In [31]:
all_players = list(p1.keys())

In [32]:
print(p1)
print(p2)

{'Huskies_D1': 52, 'Huskies_D2': 36, 'Huskies_D3': 48, 'Huskies_D4': 17, 'Huskies_D5': 17, 'Huskies_F1': 11, 'Huskies_F2': 38, 'Huskies_F3': 9, 'Huskies_G1': 12, 'Huskies_M1': 52, 'Huskies_M2': 20, 'Huskies_M3': 45, 'Huskies_M4': 9, 'Huskies_M5': 3, 'Opponent1_D1': 15, 'Opponent1_D2': 22, 'Opponent1_D3': 24, 'Opponent1_D4': 8, 'Opponent1_F1': 4, 'Opponent1_F2': 17, 'Opponent1_F3': 8, 'Opponent1_F4': 3, 'Opponent1_F5': 6, 'Opponent1_G1': 14, 'Opponent1_M1': 32, 'Opponent1_M2': 17, 'Opponent1_M3': 27}
{'Huskies_D1': 44, 'Huskies_D2': 30, 'Huskies_D3': 47, 'Huskies_D4': 23, 'Huskies_D5': 20, 'Huskies_F1': 19, 'Huskies_F2': 46, 'Huskies_F3': 13, 'Huskies_G1': 12, 'Huskies_M1': 51, 'Huskies_M2': 15, 'Huskies_M3': 37, 'Huskies_M4': 8, 'Huskies_M5': 4, 'Opponent1_D1': 17, 'Opponent1_D2': 18, 'Opponent1_D3': 23, 'Opponent1_D4': 7, 'Opponent1_F1': 7, 'Opponent1_F2': 19, 'Opponent1_F3': 12, 'Opponent1_F4': 8, 'Opponent1_F5': 9, 'Opponent1_G1': 11, 'Opponent1_M1': 29, 'Opponent1_M2': 19, 'Opponen

In [33]:
shoot_lost = {}
for k in p1.keys():
    shoot_lost[k] = p2[k]-p1[k]
shoot_lost

{'Huskies_D1': -8,
 'Huskies_D2': -6,
 'Huskies_D3': -1,
 'Huskies_D4': 6,
 'Huskies_D5': 3,
 'Huskies_F1': 8,
 'Huskies_F2': 8,
 'Huskies_F3': 4,
 'Huskies_G1': 0,
 'Huskies_M1': -1,
 'Huskies_M2': -5,
 'Huskies_M3': -8,
 'Huskies_M4': -1,
 'Huskies_M5': 1,
 'Opponent1_D1': 2,
 'Opponent1_D2': -4,
 'Opponent1_D3': -1,
 'Opponent1_D4': -1,
 'Opponent1_F1': 3,
 'Opponent1_F2': 2,
 'Opponent1_F3': 4,
 'Opponent1_F4': 5,
 'Opponent1_F5': 3,
 'Opponent1_G1': -3,
 'Opponent1_M1': -3,
 'Opponent1_M2': 2,
 'Opponent1_M3': -9}

In [34]:
m1 = np.zeros(shape=(14,14))
m2 = np.zeros(shape=(13,13))

In [35]:
for i in range(len(pe[(pe.MatchID == 1)])):
    if pe['TeamID'][i] == 'Huskies':
        m1[all_players.index(pe['OriginPlayerID'][i]),
            all_players.index(pe['DestinationPlayerID'][i])] += 1
    else:
        m2[all_players.index(pe['OriginPlayerID'][i])-14,
            all_players.index(pe['DestinationPlayerID'][i])-14] += 1

In [36]:
print(m1)

[[ 0. 14.  8.  1.  3.  3.  3.  1.  2. 11.  1.  4.  1.  0.]
 [11.  0. 18.  0.  0.  1.  3.  0.  1.  1.  0.  1.  0.  0.]
 [ 6.  6.  0.  9.  0.  1.  2.  1.  6.  4.  5.  6.  1.  1.]
 [ 0.  1.  4.  0.  0.  1.  2.  2.  0.  1.  3.  2.  1.  0.]
 [ 1.  0.  0.  0.  2.  1.  8.  0.  0.  4.  0.  1.  0.  0.]
 [ 2.  0.  0.  0.  1.  0.  5.  1.  0.  1.  0.  0.  0.  1.]
 [ 3.  0.  4.  2.  4.  3.  0.  1.  0. 14.  0.  4.  2.  1.]
 [ 0.  1.  1.  0.  0.  1.  3.  0.  0.  0.  1.  2.  0.  0.]
 [ 2.  0.  2.  0.  2.  2.  0.  0.  1.  3.  0.  0.  0.  0.]
 [13.  3.  0.  3.  2.  5. 10.  2.  1.  1.  1.  8.  2.  1.]
 [ 0.  2.  2.  4.  0.  1.  0.  2.  1.  1.  0.  7.  0.  0.]
 [ 6.  3.  8.  2.  6.  0.  6.  1.  0.  9.  4.  0.  0.  0.]
 [ 0.  0.  0.  2.  0.  0.  2.  2.  0.  1.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.  0.  0.  0.  0.  0.  1.  0.]]
